import React, { useState } from "react";
import {
  Download,
  RotateCcw,
  Share2,
  Maximize2,
  Check,
  Sparkles,
  Copy,
  Layers,
} from "lucide-react";
import { GeneratedImage as GeneratedImageType } from "../types.js";

interface GeneratedImageProps {
  image: GeneratedImageType;
  onOpenViewer: (imageUrl: string) => void;
  onRegenerate?: (prompt: string) => void;
}

export const GeneratedImage: React.FC<GeneratedImageProps> = ({
  image,
  onOpenViewer,
  onRegenerate,
}) => {
  const [copied, setCopied] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  const handleDownload = (e: React.MouseEvent) => {
    e.stopPropagation();
    const a = document.createElement("a");
    a.href = image.imageUrl;
    a.download = `chat-gpr-generated-image-${Date.now()}.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleShare = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (navigator.share) {
      try {
        await navigator.share({
          title: "CHAT GPR AI Generated Image",
          text: image.prompt,
          url: window.location.href,
        });
      } catch {
        // Fallback to copy link
        handleCopyLink();
      }
    } else {
      handleCopyLink();
    }
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(image.imageUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div
      id="chat-gpr-generated-image-card"
      className="my-3 max-w-xl w-full rounded-2xl bg-[#14171E] border border-[#242933] overflow-hidden shadow-2xl transition-all hover:border-[#6366F1]/40 group"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {/* Header Banner */}
      <div className="flex items-center justify-between px-4 py-2.5 bg-[#171A21] border-b border-[#242933]">
        <div className="flex items-center gap-2">
          <div className="p-1 rounded-lg bg-[#EC4899]/20 text-[#EC4899]">
            <Sparkles className="w-3.5 h-3.5" />
          </div>
          <span className="text-xs font-semibold text-white font-khmer">
            បានបង្កើតរូបភាពរួចរាល់ ✅
          </span>
        </div>

        <div className="flex items-center gap-2">
          {image.aspectRatio && (
            <span className="inline-flex items-center gap-1 text-[10px] font-mono px-2 py-0.5 rounded-md bg-[#242933] text-[#94A3B8]">
              <Layers className="w-2.5 h-2.5" />
              {image.aspectRatio}
            </span>
          )}
          <span className="text-[10px] text-[#64748B] font-mono">
            Gemini AI
          </span>
        </div>
      </div>

      {/* Main Image Viewport */}
      <div
        onClick={() => onOpenViewer(image.imageUrl)}
        className="relative cursor-pointer bg-black/40 overflow-hidden flex items-center justify-center min-h-[260px] sm:min-h-[340px] max-h-[500px]"
      >
        <img
          src={image.imageUrl}
          alt={image.prompt || "Generated by CHAT GPR"}
          className="w-full h-full object-contain max-h-[480px] rounded-b-none transition-transform duration-500 group-hover:scale-[1.015]"
          loading="lazy"
        />

        {/* Floating Expand Overlay Button */}
        <div
          className={`absolute top-3 right-3 p-2 rounded-xl bg-black/70 hover:bg-black text-white transition-all backdrop-blur-md ${
            isHovered ? "opacity-100 scale-100" : "opacity-0 scale-95"
          }`}
          title="ចុចដើម្បីពង្រីក / Click to enlarge"
        >
          <Maximize2 className="w-4 h-4" />
        </div>
      </div>

      {/* Prompt Caption */}
      {image.prompt && (
        <div className="px-4 py-2.5 bg-[#12151B] border-t border-[#1E232E] text-xs text-[#CBD5E1] font-khmer">
          <p className="line-clamp-2 leading-relaxed">
            <span className="font-semibold text-[#818CF8]">Prompt: </span>
            {image.prompt}
          </p>
        </div>
      )}

      {/* Action Buttons Toolbar: Download, Regenerate, Share */}
      <div className="flex items-center justify-between px-4 py-3 bg-[#171A21] border-t border-[#242933]">
        {/* Left Actions: Download */}
        <button
          onClick={handleDownload}
          id="btn-download-image"
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#242933] hover:bg-[#323946] border border-[#323946] text-white text-xs font-semibold font-khmer transition-all active:scale-95 shadow-sm"
          title="ទាញយករូបភាព (Download PNG)"
        >
          <Download className="w-3.5 h-3.5 text-[#818CF8]" />
          <span>ទាញយក / Download</span>
        </button>

        {/* Right Actions: Regenerate & Share */}
        <div className="flex items-center gap-2">
          {onRegenerate && image.prompt && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onRegenerate(image.prompt);
              }}
              id="btn-regenerate-image"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#6366F1]/20 hover:bg-[#6366F1]/30 border border-[#6366F1]/40 text-[#A5B4FC] hover:text-white text-xs font-semibold font-khmer transition-all active:scale-95"
              title="បង្កើតរូបភាពថ្មីម្តងទៀត (Regenerate Image)"
            >
              <RotateCcw className="w-3.5 h-3.5 text-[#818CF8]" />
              <span>បង្កើតឡើងវិញ / Regenerate</span>
            </button>
          )}

          <button
            onClick={handleShare}
            id="btn-share-image"
            className="p-2 rounded-xl bg-[#242933] hover:bg-[#323946] border border-[#323946] text-[#94A3B8] hover:text-white transition-all active:scale-95"
            title="ចែករំលែក (Share or Copy Link)"
          >
            {copied ? (
              <Check className="w-3.5 h-3.5 text-green-400" />
            ) : (
              <Share2 className="w-3.5 h-3.5" />
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
